{% set version = "1.6.1" %}
{% set unixsha256 = "5f7ad6f2934561beb296d472f77034033c38a89a2ec2aeba78edcbb0034af80e" %}
{% set osxsha256 = "a50eb924e0902690152f88b7e9c5b7fe4ad371bc65dc228a53911cba4e3f8a7c" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [unix]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64-static.tar.gz  # [unix]
  sha256: {{ unixsha256 }}  # [unix]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]

build:
  number: 0
  skip: True  # [win] 

requirements:
  run:
    - gmp >=5.0.1,<7

test:
  commands:
    - stack --help

about:
  home: www.haskellstack.org
  license: BSD3-like
  summary: 'Stack is a cross-platform program for developing Haskell projects.'
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
