travis:
  secure:
    BINSTAR_TOKEN: VcCoYcjuh8j8uYUUjkaiF1TfzlVHtCEj6QtDC5LE62XHxsZ2XrmLam5ZpaMIWTd3BTbVWDUY28vUhCuWqeplkhgIvdl0+IWxI6Mf1RH5pQRiPKyS4u91d3uBv+LzlPguvrRPACd7uXtXqdj1lO5m9FNA8WUC7WYW9QrvHpUzi+/K7F3PJWWFZs404otEHtWeb5S4sTRkuZXnCoQeD+bLqwucWuTPbOb6GSxXSGUfmVjxbWJB+HI9M/mWY6mQjCBz5uw9giO71q1f5KpajH2l3qwnSZ625QgD12H0CflGMj9cVqh1leqkgbtNnIGFSTe00Rf2ToKLvFnhpAOTi1xOlqizjo101q2/d8pLUJzooqlwzRbFiXxD/o5Mn84d5MBv5GPjArDe1vN1FosJEths3jXXkCbiW0jNevKmYAblcF5dW9sJF9LnYnjneJ/FXyTa7doCsIUaLsAW/MyPNMJOVRBQjl7A9G2mT2qLuHrRmzfwlQOBhuOnuPJtoBnCN6b2mZ3cLJthM/7SQm8kGCD81dU/IXgizfCSJCIJbX+VmaFAK7Mc3brvqkLXWiXLvIWOjOL20MLSWwuJzgGYQexwM/JOsXK5oMMf3hnNa4F7PKd4PTyHOpTsYZaBLjvBX5+6dYzLUVUddrv5cHv/MGJUdGCnlYhi44YHmEv3zE+nQnc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
