travis:
  secure:
    BINSTAR_TOKEN: nlrNoNA2jL/FB9HbG5GdzIRKbgubQLiEksAEpKSRzdhq4U8oTdU0R7dKDbGA+DS1G7nhfj5rPynNKR1dhzIDcKReyNtxN76a0Ml2mChDWe9Auh5EUvrSQyuVGsWvX51ONw6BD6oBcJr6BraycKbT4y48yoi3l0aIM3NGVZ7g5SGUMpvIhKK5UsP+jwuRVSt8fo3TK+qH2clylMeGaSu5oNA+CZJ86nXmMJg8i6U/HfRNpjc83ITEGc2HS/lfiLzgRaVz3ewrrn7V6o8l5KU+fQJoquqrpXEFmVibWNsvNGd0A4e+kT5EWY3iLoIFsJiJINp6jbCGV7BpEqLN5H9obTF/1QQHUnesduHae0IMiv2p6ILGxiMYEYdre4DKPiGFdOHwn0haq9CbKhdDTphSyMc7vnnceM0hDj/hrXMgwPpvxrkqiGDUnRni5pEGrSN0luBmPOksheo9ok0cffCTGC8FXa/ZnzhqUF4PA+v9YzPMisfY0IRFq3WCVWabsxFlCe4qKndul0jI3EKbWKCLQxd8x2lestnrT5mA+JtLWsAfY65My+mAIRf9se6EPch3gLLStry9DjRHpcm+WCQRzJEK7PHg5Xm30KAFCGsojGYVGIqUWXgs/Eil+XMroYF7l+5vMCIG46V/8YyYF7AeTyyEfJXuZIRGC7zqIg8T3jY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
